config/routes.rb
Rails.application.routes.draw do
  root 'pages#landing'

  resources :portfolios
  resources :stocks, only: [:index, :show] do
    post 'transactions/buy', to: 'transactions#buy', on: :member
    post 'transactions/sell', to: 'transactions#sell', on: :member
  end
  
  resources :transactions, only: [:index] do
    collection do
      post :buy
      post :sell
    end
  end
  
  #admin routes
  get 'admin/pending_traders', to: 'admin_pages#pending_traders'
  resources :admin_pages, path: 'admin', as: 'admin_pages'

  #trader routes
  get 'trader/trader_dashboard', to: 'trader_pages#show'
  post 'trader/trader_dashboard', to: 'trader_pages#deposit'


  devise_for :admins,  controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations'
  }
  
  devise_for :traders,  controllers: {
     sessions: 'traders/sessions',
     registrations: 'traders/registrations'
   }
   
  match "*path", to: "application#page_not_found", via: :all
end

app/views/shared/_admin_menu.html.erb
<li>
  <%= link_to admin_pages_path, class: 'block px-4 py-2 hover:rounded hover:bg-hover' do %>
    <i class="fa-solid fa-list mr-2"></i>
    <span class="md:inline-block">Traders</span>
  <% end %>
</li>
<div class="py-4 border-t border-gray-200 dark:border-gray-600 max-h-[500px] overflow-y-auto"></div>
<li class="block px-4 py-2 hover:rounded hover:bg-hover">
  <i class="fa-solid fa-user mr-2"></i>
  <span class="md:inline-block">Admin</span>
</li>
<li>
  <%= link_to destroy_admin_session_path, data: { turbo_method: :delete, turbo_confirm: "Log out?" }, class: 'block px-4 py-2 hover:rounded hover:bg-hover' do %>
    <i class="fa-solid fa-arrow-right-from-bracket mr-2"></i>
    <p class="hidden sm:inline-flex"> Logout </p>
  <% end %>
</li>

app/views/shared/_header.html.erb
<% if current_trader.present? || current_admin.present? %>
<nav class="navbar bg-strongdark w-full h-16 flex items-center justify-between px-6 py-4 drop-shadow-lg">
    <div class="flex items-center">
      <%= link_to 'TradeXpert', root_path, class: "text-2xl font-bold txt-gradient" %> 
    </div>
    
    <div class="w-max flex justify-center items-center text-sky-50">
      <% if current_trader.present? %>
        <div class="flex items-center gap-2">
        <p>Hello, <%= current_trader.first_name %>👋</p>
          <%= link_to destroy_trader_session_path, data: { turbo_method: :delete, turbo_confirm: "Log out?" }, class: "actions btn--subv1" do %>
          <i class="fa-solid fa-arrow-right-from-bracket"></i>
          <p class="hidden sm:inline-flex"> Logout </p>
          <% end %>
        </div>
      <% elsif current_admin.present? %>
        <div class="flex items-center gap-2">
          <p>Hello, Admin👋</p>
          <%= link_to destroy_admin_session_path, data: { turbo_method: :delete, turbo_confirm: "Log out?" }, class: "actions btn--subv1" do %>
            <i class="fa-solid fa-arrow-right-from-bracket"></i>
            <p class="hidden sm:inline-flex"> Logout </p>
          <% end %>
        </div>
      <% end %>
    </div>
</nav>
<% end %>

app/views/shared/_notifications.html.erb
<div>
    <% if flash[:notice] %>
        <div 
        id="toast-success" 
        class="transition transform duration-1000 absolute bottom-5 right-5 flex items-center w-full max-w-xs p-4 mb-4 text-gray-500 bg-white rounded-lg shadow dark:text-gray-400 dark:bg-gray-800"
        data-controller="notification"
        data-notification-delay-value="4000"
        data-transition-enter-from="opacity-0 translate-x-6"
        data-transition-enter-to="opacity-100 translate-x-0"
        data-transition-leave-from="opacity-100 translate-x-0"
        data-transition-leave-to="opacity-0 translate-x-6"
        >
        
        <div class="inline-flex items-center justify-center flex-shrink-0 w-8 h-8 text-green-500 bg-green-100 rounded-lg dark:bg-green-800 dark:text-green-200">
        <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
            <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5Zm3.707 8.207-4 4a1 1 0 0 1-1.414 0l-2-2a1 1 0 0 1 1.414-1.414L9 10.586l3.293-3.293a1 1 0 0 1 1.414 1.414Z"/>
        </svg>
        <span class="sr-only">Check icon</span>
        </div>
        <div class="ms-3 text-sm font-normal"><%= flash[:notice] %></div>
        <button type="button" class="ms-auto -mx-1.5 -my-1.5 bg-white text-gray-400 hover:text-gray-900 rounded-lg focus:ring-2 focus:ring-gray-300 p-1.5 hover:bg-gray-100 inline-flex items-center justify-center h-8 w-8 dark:text-gray-500 dark:hover:text-white dark:bg-gray-800 dark:hover:bg-gray-700" data-dismiss-target="#toast-success" aria-label="Close">
            <span class="sr-only">Close</span>
            <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
            </svg>
        </button>
        </div>
    <% end %>

    <% if flash[:alert] %>
        <div id="toast-warning" 
        class="transition transform duration-1000 absolute bottom-5 right-5 flex items-center w-full max-w-xs p-4 text-gray-500 bg-white rounded-lg shadow dark:text-gray-400 dark:bg-gray-800"
        data-controller="notification"
        data-notification-delay-value="4000"
        data-transition-enter-from="opacity-0 translate-x-6"
        data-transition-enter-to="opacity-100 translate-x-0"
        data-transition-leave-from="opacity-100 translate-x-0"
        data-transition-leave-to="opacity-0 translate-x-6"
        >
        
        <div class="inline-flex items-center justify-center flex-shrink-0 w-8 h-8 text-orange-500 bg-orange-100 rounded-lg dark:bg-orange-700 dark:text-orange-200">
        <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
            <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM10 15a1 1 0 1 1 0-2 1 1 0 0 1 0 2Zm1-4a1 1 0 0 1-2 0V6a1 1 0 0 1 2 0v5Z"/>
        </svg>
        <span class="sr-only">Warning icon</span>
        </div>
        <div class="ms-3 text-sm font-normal"><%= flash[:alert] %></div>
        <button type="button" class="ms-auto -mx-1.5 -my-1.5 bg-white text-gray-400 hover:text-gray-900 rounded-lg focus:ring-2 focus:ring-gray-300 p-1.5 hover:bg-gray-100 inline-flex items-center justify-center h-8 w-8 dark:text-gray-500 dark:hover:text-white dark:bg-gray-800 dark:hover:bg-gray-700" data-dismiss-target="#toast-success" aria-label="Close">
            <span class="sr-only">Close</span>
            <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
            </svg>
        </button>
        </div>
    <% end %>
</div>

app/views/shared/_sidebar.html.erb
<% if current_trader.present? || current_admin.present? %>
  <nav class="flex">
    <div class="w-64 p-4 bg-strongdark h-screen sticky top-0 z-999">
      <div class="mb-4">
        <%= link_to 'TradeXpert', root_path, class: "text-2xl font-bold txt-gradient" %> 
      </div>
      
      <ul class="flex-col text-white">
        <% if current_admin.present? %>
          <%= render 'shared/admin_menu' %>
        <% elsif current_trader.present? %>
          <%= render 'shared/trader_menu' %>
        <% end %>
      </ul>
    </div>
  </nav>
<% end %>

app/views/shared/_trader_menu.html.erb
<li>
  <%= link_to trader_trader_dashboard_path, class: 'block px-4 py-2 hover:rounded hover:bg-hover' do %>
    <i class="fa-solid fa-gauge mr-2"></i>
    <span class="md:inline-block">Dashboard</span>
  <% end %>
</li>
<li>
  <%= link_to portfolios_path, class: 'block px-4 py-2 hover:rounded hover:bg-hover' do %>
    <i class="fa-solid fa-briefcase mr-2"></i>
    <span class="md:inline-block">Portfolio</span>
  <% end %>
</li>
<li>
  <%= link_to stocks_path, class: 'block px-4 py-2 hover:rounded hover:bg-hover' do %>
    <i class="fa-solid fa-chart-simple mr-2"></i>
    <span class="md:inline-block">Stocks</span>
  <% end %>
</li>
<li class="mb-2">
  <%= link_to transactions_path, class: 'block px-4 py-2 hover:rounded hover:bg-hover' do %>
    <i class="fa-solid fa-folder-open mr-2"></i>
    <span class="md:inline-block">Transaction</span>
  <% end %>
</li>
<div class="py-4 border-t border-gray-200 dark:border-gray-600 max-h-[500px] overflow-y-auto"></div>
<li class="block px-4 py-2 hover:rounded hover:bg-hover">
  <i class="fa-solid fa-user mr-2"></i>
  <span class="md:inline-block"><%= current_trader.first_name %></span>
</li>
<li>
  <%= link_to destroy_trader_session_path, data: { turbo_method: :delete, turbo_confirm: "Log out?" }, class: 'block px-4 py-2 hover:rounded hover:bg-hover' do %>
    <i class="fa-solid fa-arrow-right-from-bracket mr-2"></i>
    <p class="hidden sm:inline-flex"> Logout </p>
  <% end %>
</li>