config/routes.rb
Rails.application.routes.draw do
  root 'pages#landing'

  resources :portfolios
  resources :stocks, only: [:index, :show] do
    post 'transactions/buy', to: 'transactions#buy', on: :member
    post 'transactions/sell', to: 'transactions#sell', on: :member
  end
  
  resources :transactions, only: [:index] do
    collection do
      post :buy
      post :sell
    end
  end
  
  #admin routes
  get 'admin/pending_traders', to: 'admin_pages#pending_traders'
  resources :admin_pages, path: 'admin', as: 'admin_pages'

  #trader routes
  get 'trader/trader_dashboard', to: 'trader_pages#show'
  post 'trader/trader_dashboard', to: 'trader_pages#deposit'


  devise_for :admins,  controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations'
  }
  
  devise_for :traders,  controllers: {
     sessions: 'traders/sessions',
     registrations: 'traders/registrations'
   }
   
  match "*path", to: "application#page_not_found", via: :all
end

app/controllers/admin_pages_controller.rb
class AdminPagesController < ApplicationController
  before_action :require_admin
  before_action :set_trader, only: [:show, :edit, :update]

  def index
    @q = Trader.where(approved: true).ransack(params[:q])
    @pagy, @traders = pagy(@q.result(distinct: true).sorted)
  end

  def pending_traders
    @q = Trader.where.not(confirmed_at: nil).where(approved: false).ransack(params[:q])
    @pagy, @traders = pagy(@q.result(distinct: true).sorted)
  end

  def show
    if @trader
      @transaction = @trader.transactions
    else
      redirect_to admin_pages_path, alert: "Data not found."
    end
  end

  def new
    @trader = Trader.new
  end

  def create
    @trader = Trader.new(trader_params.merge(admin_created: true, approved: true, confirmed_at: Time.zone.now))
    if @trader.save
      redirect_to admin_pages_path, notice: 'Trader was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @trader.update(trader_params)
      TraderMailer.account_approved_email(@trader).deliver_now if @trader.approved?
      redirect_to admin_pages_path, notice: 'Trader was successfully updated.'
    else
      render :edit
    end
  end

  private

  def set_trader
    @trader = Trader.find_by(id: params[:id])
    redirect_to admin_pages_path, alert: "Trader not found." unless @trader
  end

  def require_admin
    redirect_to root_path, alert: "You are not authorized to access this page." unless admin_signed_in?
  end

  def trader_params
    params.require(:trader).permit(:first_name, :last_name, :email, :password, :password_confirmation, :admin_created, :approved)
  end
end

app/views/admin_pages/_form.html.erb
<div class="mx-auto max-w-7xl flex justify-center items-center h-screen">
  <div class="sm:mx-auto sm:w-full sm:max-w-md ">
    <div class="p-8 rounded-md bg-clip-padding backdrop-filter backdrop-blur-sm bg-opacity-10"> 
      <div class="mb-4 text-center mt-2 text-white font-medium italic text-4xl">
          <%= @trader.new_record? ? 'Add' : 'Edit' %>
          <span class="font-bold not-italic">Trader</span>
      </div>
      <%= form_with(model: @trader, url: @trader.new_record? ? admin_pages_path : admin_page_path(@trader), method: @trader.new_record? ? :post : :patch, local: false) do |f| %>
        <div class="grid md:grid-cols-2 md:gap-3 mb-4">
          <div>
            <%= f.label :first_name, class: "text-sm font-medium text-white" %><br />
            <%= f.text_field :first_name, autocomplete: "off", placeholder: "Juan",  class: "w-full rounded-md border border-gray-300 shadow-md shadow-gray-900/10" %>
          </div>
          <div>
            <%= f.label :last_name, class: "text-sm font-medium text-white" %><br />
            <%= f.text_field :last_name, autocomplete: "off", placeholder: "Dela Cruz",  class: "w-full rounded-md border border-gray-300 shadow-md shadow-gray-900/10" %>
          </div>
        </div>
        <div class="mb-4">
          <%= f.label :email, class: "block text-sm font-medium text-white" %>
          <%= f.email_field :email, autofocus: true, autocomplete: "off", placeholder: "name@email.com", class: "mt-1 p-2 w-full rounded-md border border-gray-300 shadow-md shadow-gray-900/10"%>
         </div>
        <% if @trader.new_record? %> 
        <div class="mb-4">
            <%= f.label :password, class: "block text-sm font-medium text-white" %>
            <%= f.password_field :password, autocomplete: "current-password", class: "mt-1 p-2 w-full rounded-md border border-gray-300 shadow-md shadow-gray-900/10 " %>
          </div>
        <% end %>
        <% if !@trader.new_record? %> 
          <div class="mt-1">
            <label class="inline-flex items-center">
              <%= f.check_box :approved, { checked: @trader.approved }, true, false %>
              <span class="ml-2 text-sm text-white">Approved</span>
            </label>
          </div>
        <% end %>

        <div class="mb-4 pt-2">
          <%= f.submit "Submit", class: "w-full bg-gradient rounded-big focus:ring-4 focus:outline-none focus:ring-blue-300 text-white font-bold text-xl py-2.5 shadow-md shadow-gray-900/10" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin_pages/_nav_links.html.erb
<div class="flex justify-between items-center px-6 py-2">
<div>
  <%= link_to 'Approved', admin_pages_path, class: 'btn-secondary mr-4' %>
  <%= link_to 'Pending', admin_pending_traders_path, class: 'btn-secondary' %>
</div>

<form> 
<%= search_form_for @q, url: admin_pages_path do |f| %>  
<label for="default-search" class="mb-2 text-sm font-medium text-gray-900 sr-only dark:text-white">Search</label>
  <div class="relative">
    <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
      <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
      <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
      </svg>
    </div>
  <%= f.search_field :first_name_or_last_name_or_email_cont, class: "block w-full p-4 ps-10 text-sm text-white border border-none rounded-lg bg-strongdark", placeholder: "Search...", autocomplete: "off", required: true %>
  <% end %>
  </div>
</form>

</div>

app/views/admin_pages/_traders_table.html.erb
<div class="mt-12">
    <div class="relative overflow-x-auto bg-lightdark shadow-md sm:rounded-lg">
        <%= render 'nav_links' %>
        <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
            <thead class="text-xs text-gray-700 uppercase bg-lightdark">
                <tr class="border-b border-gray-500">
                    <th scope="col" class="px-6 py-3">
                        ID
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Name
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Email
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Wallet
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Action
                    </th>
                </tr>
            </thead>
            <tbody>
            <% @traders.each do |trader| %>
                <tr class="border-b border-gray-500 bg-lightdark">
                    <th scope="row" class="px-6 py-4 font-medium text-white whitespace-nowrap">
                        <%= trader.id %>
                    </th>
                    <td class="px-6 py-4">
                        <%= link_to "#{trader.first_name} #{trader.last_name}", admin_page_path(trader.id), class: "text-sm text-white no-underline font-light px-6 py-4 whitespace-nowrap" %>
                    </td>
                    <td class="px-6 py-4">
                        <%= trader.email %>
                    </td>
                    <td class="px-6 py-4">
                        $ <%= trader.wallet %>
                    </td>
                    <td class="px-6 py-4">
                        <%= link_to edit_admin_page_path(trader) do %>
                        <i class="fas fa-edit mr-2"></i>
                        <span class="text-white">Edit</span>
                        <% end %> 
                    </td>
                </tr>
            <% end %>
            </tbody>
        </table>
        <div class="py-4 px-2 flex justify-center">
        <%== pagy_nav(@pagy) %>
        </div>
    </div>
</div>

app/views/admin_pages/_transactions.html.erb
<div class="mt-8">
    <div class="relative overflow-x-auto bg-lightdark shadow-md sm:rounded-lg">
    <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
            <thead class="text-xs text-gray-700 uppercase bg-lightdark">
            <tr class="border-b border-gray-500">
                <th scope="col" class="px-6 py-3">
                    Stock
                </th>
                <th scope="col" class="px-6 py-3">
                    Transaction Type
                </th>
                <th scope="col" class="px-6 py-3">
                    Number of Shares
                </th>
                <th scope="col" class="px-6 py-3">
                    Price
                </th>
                <th scope="col" class="px-6 py-3">
                    Date
                </th>
            </tr>
            </thead>
            <tbody>
                <% @transaction.each do |t| %>
                <tr class="border-b border-gray-500 bg-lightdark">
                    <th scope="row" class="px-6 py-4 font-medium text-white whitespace-nowrap">
                        <%= t.stock.ticker_symbol %> - <%= t.stock.company_name %>
                    </th>
                    <td class="px-6 py-4">
                        <%= t.transaction_type %>
                    </td>
                    <td class="px-6 py-4">
                        <%= t.number_of_shares %>
                    </td>
                    <td class="px-6 py-4">
                        <%= number_to_currency(t.price) %>
                    </td>
                    <td class="px-6 py-4">
                        <%= t.created_at.strftime("%Y-%m-%d") %>
                    </td>
                </tr>
                <% end %>
            </tbody>
    </table>
    </div>
</div>

app/views/admin_pages/edit.html.erb
<%= render 'form' %>

app/views/admin_pages/index.html.erb
<div class="w-full px-8" style="height: calc(100vh - 64px);">
<div class="mt-8 flex justify-between">
  <h1 class="text-4xl font-bold text-white">Traders</h1>
  <%= link_to new_admin_page_path, class: 'btn-main' do %>
    <div class="flex items-center gap-4 text-balance">
      <p class="font-bold">Add New Trader</p>
      <i class="fa-solid fa-plus grid place-items-center text-xs hover:text-sky-200"></i>
    </div>
  <% end %>
</div>
<%= render 'traders_table' %>
</div>

app/views/admin_pages/new.html.erb
<%= render 'form' %>

app/views/admin_pages/pending_traders.html.erb
<div class="w-full px-8" style="height: calc(100vh - 64px);">
<div class="mt-8 flex justify-between">
  <h1 class="text-4xl font-bold text-white">Traders</h1>
  <%= link_to new_admin_page_path, class: 'btn-main' do %>
    <div class="flex items-center gap-4 text-balance">
      <p class="font-bold">Add New Trader</p>
      <i class="fa-solid fa-plus grid place-items-center text-xs hover:text-sky-200"></i>
    </div>
  <% end %>
</div>

<%= render 'traders_table' %>
</div>

app/views/admin_pages/show.html.erb
<div class="w-full px-12 py-8">
<div class="text-white flex justify-between items-center"> 
    <h1 class="font-bold text-4xl">Transactions</h1>
    <div>
    <div>
        <p>Full name:
        <span class="font-bold"><%= @trader.first_name %> <%= @trader.last_name %></span>
        </p>
    </div>
    <div>
        <p>Email address:
        <span class="font-bold"><%= @trader.email %></span>
        </p>
    </div>
    <div>
        <p>Activated: 
        <span class="font-bold"><%= @trader.approved? %></span>
        </p>
    </div>
    </div>
</div>

<% if @transaction.present? %>
<%= render 'transactions' %>
<% else %>
    <div class="text-white text-center italic border-t">
        <p class="mt-4">There are currently no transactions on record.</p>
    </div>
<% end %>
</div>