config/routes.rb
Rails.application.routes.draw do
  root 'pages#landing'

  resources :portfolios
  resources :stocks, only: [:index, :show] do
    post 'transactions/buy', to: 'transactions#buy', on: :member
    post 'transactions/sell', to: 'transactions#sell', on: :member
  end
  
  resources :transactions, only: [:index] do
    collection do
      post :buy
      post :sell
    end
  end
  
  #admin routes
  get 'admin/pending_traders', to: 'admin_pages#pending_traders'
  resources :admin_pages, path: 'admin', as: 'admin_pages'

  #trader routes
  get 'trader/trader_dashboard', to: 'trader_pages#show'
  post 'trader/trader_dashboard', to: 'trader_pages#deposit'


  devise_for :admins,  controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations'
  }
  
  devise_for :traders,  controllers: {
     sessions: 'traders/sessions',
     registrations: 'traders/registrations'
   }
   
  match "*path", to: "application#page_not_found", via: :all
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
    before_action :require_trader
    before_action :set_client                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
  
    def index
        @transactions = current_trader.transactions.order(created_at: :desc)
        if params[:search].present?
            @search_term = params[:search]
            searched_transactions = @transactions.joins(:stock).where("stocks.company_name ILIKE :search_start OR stocks.ticker_symbol ILIKE :search_start", search_start: "#{params[:search]}%")

            if searched_transactions.empty?
                @transactions = current_trader.transactions.order(created_at: :desc)
                flash[:alert] = "No results found for '#{@search_term}'"
            else
                @transactions = searched_transactions
            end
        end

        @pagy, @paginated_transactions = pagy(@transactions, items: 5)

        @cash_balance = current_trader.wallet
    end
  
    def buy
        set_transaction_data
    
        if current_trader.wallet >= @total_price
            begin
                Transaction.execute_transaction(@quote, current_trader, @symbol, @quantity, 'buy', @total_price)
                flash[:notice] = 'Yay! Stock purchased successfully. It\'s gonna be a great investment!'
                redirect_to portfolios_path
            rescue ActiveRecord::RecordInvalid
                flash[:alert] = 'It seems like you entered an invalid number of shares. Try again!'
                redirect_to stock_path
            end
        else
            flash[:alert] = 'Oops! Insufficient funds to buy the stock. Top up your wallet!'
            redirect_to stock_path
        end
    
        rescue IEX::Errors::SymbolNotFoundError
            handle_error
    end
  
    def sell
        set_transaction_data

        portfolio = current_trader.portfolios.find_by(stock_id: Stock.find_by(ticker_symbol: @symbol)&.id)
        
        if portfolio.nil? || portfolio.number_of_shares <= @quantity
            flash[:alert] = "Looks like you're running low on shares. Time to stock up before selling!"
            redirect_to stock_path
        end
        
        Transaction.execute_transaction(@quote, current_trader, @symbol, @quantity, 'sell', @total_price)
            flash[:notice] = 'Stock successfully sold! Keep the profits rolling in!'
            redirect_to portfolios_path
        rescue ActiveRecord::RecordInvalid
            handle_error('It seems like you entered an invalid number of shares. Try again!')
            redirect_to stock_path
        
        rescue IEX::Errors::SymbolNotFoundError
            handle_error("Uh-oh! We couldn't find that symbol. Please check the symbol and try again.")
    end
    
    private

    def set_transaction_data
        @symbol = params[:id]
        @quote = @client.quote(@symbol)
        @quantity = params[:quantity].to_i
        @total_price = @quantity * @quote.latest_price
    end
  
    def handle_error(message)
        flash[:alert] = message
        redirect_to stocks_path
    end

    def require_trader
        redirect_to root_path, alert: "You are not authorized to access this page." unless trader_signed_in?
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_buy.html.erb
<%= form_with(url: transactions_buy_stock_path(id: @quote.symbol), method: :post) do |f| %>
  <form>   
    <div class="relative">
      <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
      </div>
      <%= f.number_field :quantity, class: "block w-full p-4 ps-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500", placeholder: "Number of shares", required: true %>
      <button type="submit" class="text-white absolute end-2.5 bottom-2.5 bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Buy</button>
    </div>
  </form>
<% end %>

app/views/transactions/_nav_links.html.erb
<div class="flex justify-between items-center px-6 py-2">
<p class=" text-gray-700 font-bold">Cash Balance: <span class="text-white"><%= number_to_currency(@cash_balance) %></span></p>
<form> 
<%=  form_tag transactions_path, method: :get, novalidate: true do %>  
<label for="default-search" class="mb-2 text-sm font-medium text-gray-900 sr-only dark:text-white">Search</label>
  <div class="relative">
    <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
      <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
      <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
      </svg>
    </div>
  <%= text_field_tag :search, params[:search], class: "block w-full p-4 ps-10 text-sm text-white border border-none rounded-lg bg-strongdark", placeholder: "Search...", autocomplete: "off", required: true %>
  <% end %>
  </div>
</form>
</div>

app/views/transactions/_sell.html.erb
<%= form_with(url: transactions_sell_stock_path(id: @quote.symbol), method: :post) do |f| %>
<form>   
    <div class="relative">
        <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
        </div>
        <%= f.number_field :quantity, class: "block w-full p-4 ps-10 text-sm border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500", placeholder: "Number of shares", required: true %>
        <button type="submit" class="text-white absolute end-2.5 bottom-2.5 bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Sell</button>
    </div>
</form>
<% end %>

app/views/transactions/_transaction_table.html.erb
<div class="relative overflow-x-auto bg-lightdark shadow-md sm:rounded-lg">
    <%= render 'nav_links' %>
    <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
        <thead class="text-xs text-gray-700 uppercase bg-lightdark">
            <tr class="border-b border-gray-500">
                <th scope="col" class="px-6 py-3">
                    Stocks
                </th>
                <th scope="col" class="px-6 py-3">
                    Trade Type
                </th>
                <th scope="col" class="px-6 py-3">
                    Quantity
                </th>
                <th scope="col" class="px-6 py-3">
                    Price per Share
                </th>
                <th scope="col" class="px-6 py-3">
                    Total Price
                </th>
                <th scope="col" class="px-6 py-3">
                    Date
                </th>
            </tr>
        </thead>
        <tbody>
        <% @paginated_transactions.each do |transaction| %>
            <tr class="border-b border-gray-500 bg-lightdark">
                <th scope="row" class="px-6 py-4 font-medium text-white whitespace-nowrap">
                    <div class="flex flex-col gap-0.5">
                        <p><%= transaction.stock.company_name %></p>
                        <p class="text-gray-500"><%= transaction.stock.ticker_symbol %></p> 
                    </div>
                </th>
                <td class="px-6 py-4">
                    <%= transaction.transaction_type %>
                </td>
                <td class="px-6 py-4">
                    <%= transaction.number_of_shares %>
                </td>
                <td class="px-6 py-4">
                    <%= number_to_currency(transaction.price / transaction.number_of_shares) %>
                </td>
                <td class="px-6 py-4">
                    <%= number_to_currency(transaction.price) %>
                </td>
                <td class="px-6 py-4">
                    <%= transaction.created_at.strftime("%Y-%m-%d") %>
                </td>
            </tr>
        <% end %>
        </tbody>
    </table>

    <div class="py-4 px-2 flex justify-center">
        <%== pagy_nav(@pagy) %>
    </div>
</div>

app/views/transactions/index.html.erb
<div class="w-full h-screen px-8">
  <div class="mt-8 mb-4 flex justify-between">
    <h1 class="text-white font-bold text-2xl">Transactions</h1>
  </div>

  <% if @transactions.present? %>
    <%= render 'transaction_table' %>
  <% else %>
    <p class="text-white text-center italic">There are currently no transactions on record.</p>
  <% end %>
</div>